#!/usr/bin/env ruby

require_relative '../config/environment'

days = Integer(ARGV[0]) rescue nil
days = 30 if days.nil?

result = RetrieveInsider.call(days: days)

if result.success?
  table = Terminal::Table.new do |t|
    t.style = { :border => :unicode_round }
    t.headings = [
      "ID",
      "股票",
      "日期",
      "名称",
      "职位",
      "股票变动数量",
      "平均价格",
      "交易价格"
    ]
    result.insiders.each {|e| t.add_row(e.values) }
    t.style = {:all_separators => true}
  end

  puts table
else
  puts result.message
end
