#!/usr/bin/env ruby

require_relative '../config/environment'
require 'date'

days = Integer(ARGV[0]) rescue nil

if days.nil?
  if Date.today.monday?
    days = 4
  else
    days = 1
  end
end

result = RetrieveLatestInstitutions.call(days: days)

if result.success?
  table = Terminal::Table.new do |t|
    t.style = { :border => :unicode_round }
    t.headings = [
      "ID",
      "股票",
      "日期",
      "机构名称",
      "持有数量",
      "市场价值",
      "占股票百分比",
      "占机构百分比",
      "机构季度变动百分比",
      "机构季度变动数量",
      "机构平均成本",
      "创建时间"
    ]

    result.institutions.each {|e| t.add_row(e.values) }
    t.style = {:all_separators => true}
  end

  puts table
else
  puts institutions.message
end
