class Exchange < Sequel::Model
end

# Table: exchanges
# ----------------------------------------------------------------------------------
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    | NOT NULL
# Indexes:
#  exchanges_pkey     | PRIMARY KEY btree (id)
#  exchanges_name_key | UNIQUE btree (name)
# Referenced By:
#  new_stocks | new_stocks_exchange_id_fkey | (exchange_id) REFERENCES exchanges(id)
#  stocks     | stocks_exchange_id_fkey     | (exchange_id) REFERENCES exchanges(id)
# ----------------------------------------------------------------------------------
