class Exchange < Sequel::Model
end

# Table: exchanges
# ----------------------------------------------------------------------------------
# Columns:
#  id   | bigint                 | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | character varying(255) | NOT NULL
# Indexes:
#  exchanges_pkey               | PRIMARY KEY btree (id)
#  sqlite_autoindex_exchanges_1 | UNIQUE btree (name)
# Referenced By:
#  new_stocks | new_stocks_exchange_id_fkey | (exchange_id) REFERENCES exchanges(id)
#  stocks     | stocks_exchange_id_fkey     | (exchange_id) REFERENCES exchanges(id)
# ----------------------------------------------------------------------------------
