class Firm < Sequel::Model
  one_to_many :institutions
end

# Table: firms
# -------------------------------------------------------------------------------------
# Columns:
#  id           | bigint                 | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name         | character varying(255) | NOT NULL
#  display_name | character varying(255) |
# Indexes:
#  firms_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  institutions | institutions_firm_id_fkey | (firm_id) REFERENCES firms(id)
# -------------------------------------------------------------------------------------
