class Insider < Sequel::Model
end

# Table: insiders
# --------------------------------------------------------------
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    |
# Indexes:
#  insiders_pkey1 | PRIMARY KEY btree (id)
# --------------------------------------------------------------
