class InsiderHistory < Sequel::Model
  many_to_one :stock
  many_to_one :insider
end

# Table: insider_histories
# -----------------------------------------------------------------------------------------------
# Columns:
#  id                | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  date              | date                        | NOT NULL
#  title             | text                        | NOT NULL
#  number_of_holding | integer                     |
#  number_of_shares  | integer                     | NOT NULL
#  average_price     | numeric                     | NOT NULL
#  share_total_price | numeric                     | NOT NULL
#  created_at        | timestamp without time zone | NOT NULL
#  stock_id          | integer                     |
#  insider_id        | integer                     |
# Indexes:
#  insiders_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  insider_histories_insider_id_fkey | (insider_id) REFERENCES insiders(id)
#  insiders_stock_id_fkey            | (stock_id) REFERENCES stocks(id)
# -----------------------------------------------------------------------------------------------
