class Institution < Sequel::Model
  one_to_many :institution_histories

  def display_name
    name = self[:name]
    display_name = self[:display_name]
    name = "#{name} (#{display_name})" if display_name.present? and display_name != name
    name
  end
end

# Table: institutions
# -------------------------------------------------------------------------------------------------
# Columns:
#  id           | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name         | text    | NOT NULL
#  display_name | text    |
# Indexes:
#  firms_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  institution_histories | institutions_firm_id_fkey | (institution_id) REFERENCES institutions(id)
# -------------------------------------------------------------------------------------------------
