class Institution < Sequel::Model
  many_to_one :stock
  many_to_one :firm
end

# Table: institutions
# ---------------------------------------------------------------------------------------------------------------
# Columns:
#  id                                | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name                              | character varying(255)      | NOT NULL
#  number_of_holding                 | bigint                      | NOT NULL
#  market_value                      | bigint                      |
#  percent_of_shares_for_stock       | numeric                     |
#  percent_of_shares_for_institution | numeric                     |
#  quarterly_changes_percent         | numeric                     |
#  quarterly_changes                 | bigint                      |
#  market_value_dollar_string        | character varying(255)      |
#  holding_cost                      | numeric                     |
#  date                              | date                        |
#  created_at                        | timestamp without time zone |
#  stock_id                          | bigint                      |
#  firm_id                           | bigint                      |
# Indexes:
#  institutions_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  institutions_firm_id_fkey  | (firm_id) REFERENCES firms(id)
#  institutions_stock_id_fkey | (stock_id) REFERENCES stocks(id)
# ---------------------------------------------------------------------------------------------------------------
