class Institution < Sequel::Model
  many_to_one :stock
  many_to_one :firm
end

# Table: institutions
# ---------------------------------------------------------------------------------------------------------------
# Columns:
#  id                                | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  number_of_holding                 | integer                     | NOT NULL
#  market_value                      | numeric                     |
#  percent_of_shares_for_stock       | numeric                     |
#  percent_of_shares_for_institution | numeric                     |
#  quarterly_changes_percent         | numeric                     |
#  quarterly_changes                 | integer                     |
#  market_value_dollar_string        | text                        |
#  holding_cost                      | numeric                     |
#  date                              | date                        |
#  created_at                        | timestamp without time zone |
#  stock_id                          | integer                     |
#  firm_id                           | integer                     |
# Indexes:
#  institutions_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  institutions_firm_id_fkey  | (firm_id) REFERENCES firms(id)
#  institutions_stock_id_fkey | (stock_id) REFERENCES stocks(id)
# ---------------------------------------------------------------------------------------------------------------
