class InvestingLatestNews < Sequel::Model
end

# Table: investing_latest_news
# -------------------------------------------------------------------------------------------------
# Columns:
#  id                  | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  url                 | text                        | NOT NULL
#  title               | text                        | NOT NULL
#  preview             | text                        | NOT NULL
#  source              | text                        | NOT NULL
#  publish_time_string | text                        | NOT NULL
#  publish_time        | timestamp without time zone | NOT NULL
#  created_at          | timestamp without time zone | NOT NULL
# Indexes:
#  investing_latest_news_pkey               | PRIMARY KEY btree (id)
#  investing_latest_news_publish_time_index | btree (publish_time)
#  investing_latest_news_url_index          | btree (url)
# -------------------------------------------------------------------------------------------------
