class InvestingLatestNews < Sequel::Model
  def display_time
    if publish_time.is_today?
      self[:publish_time_string]
    else
      self[:publish_time].to_date
    end
  end

  def page_class
    if self.is_read == false
      # 在 render 中别 query 的同时，更改某个字段的值，这个特性 stream 不支持。
      self.update(is_read: true)
      "cyan darken-4"
    else
      "cyan darken-3"
    end
  end
end

# Table: investing_latest_news
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id                       | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  url                      | text                        | NOT NULL
#  title                    | text                        | NOT NULL
#  preview                  | text                        | NOT NULL
#  source                   | text                        | NOT NULL
#  publish_time_string      | text                        | NOT NULL
#  publish_time             | timestamp without time zone | NOT NULL
#  created_at               | timestamp without time zone | NOT NULL
#  updated_at               | timestamp without time zone |
#  textsearchable_index_col | tsvector                    | DEFAULT to_tsvector('zhparser'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(preview, ''::text)))
#  is_read                  | boolean                     | DEFAULT false
# Indexes:
#  investing_latest_news_pkey                 | PRIMARY KEY btree (id)
#  investing_latest_news_publish_time_index   | btree (publish_time)
#  investing_latest_news_textsearch_idx_index | gin (textsearchable_index_col)
#  investing_latest_news_url_index            | btree (url)
# Triggers:
#  set_updated_at | BEFORE INSERT OR UPDATE ON investing_latest_news FOR EACH ROW EXECUTE FUNCTION investing_latest_news_set_updated_at()
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
