class Jin10MessageCategory < Sequel::Model
  one_to_many :jin10_messages
end

# Table: jin10_message_categories
# -------------------------------------------------------------------------------------------------------------------------------------
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    |
# Indexes:
#  jin10_message_categories_pkey     | PRIMARY KEY btree (id)
#  jin10_message_categories_name_key | UNIQUE btree (name)
# Referenced By:
#  jin10_messages | jin10_messages_jin10_message_category_id_fkey | (jin10_message_category_id) REFERENCES jin10_message_categories(id)
# -------------------------------------------------------------------------------------------------------------------------------------
