class Jin10Message < Sequel::Model
  many_to_one :jin10_message_category
end

# Table: jin10_messages
# -------------------------------------------------------------------------------------------------
# Columns:
#  id                  | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  title               | text                        |
#  publish_date        | date                        |
#  publish_time_string | text                        |
#  category            | text                        |
#  url                 | text                        |
#  important           | boolean                     | DEFAULT false
#  created_at          | timestamp without time zone |
#  updated_at          | timestamp without time zone |
# Indexes:
#  jin10_messages_pkey                     | PRIMARY KEY btree (id)
#  jin10_messages_title_publish_date_index | UNIQUE btree (title, publish_date)
#  jin10_messages_important_index          | btree (important)
# -------------------------------------------------------------------------------------------------
