class Jin10MessageTag < Sequel::Model
  one_to_many :jin10_messages
end

# Table: jin10_message_tags
# --------------------------------------------------------------
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    |
# Indexes:
#  jin10_message_tags_pkey     | PRIMARY KEY btree (id)
#  jin10_message_tags_name_key | UNIQUE btree (name)
# --------------------------------------------------------------
