class Log < Sequel::Model
  def finished_at_string
    if finished_at.is_today?
      finished_at.strftime('今天 %H:%M')
    else
      finished_at.strftime('%Y-%m-%d %H:%M')
    end
  end

  def created_at_string
    if created_at.is_today?
      created_at.strftime('今天 %H:%M')
    else
      created_at.strftime('%Y-%m-%d %H:%M')
    end
  end
end

# Table: logs
# -----------------------------------------------------------------------------------------
# Columns:
#  id          | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  type        | character varying(255)      | NOT NULL
#  finished_at | timestamp without time zone |
#  created_at  | timestamp without time zone | NOT NULL
# Indexes:
#  logs_pkey | PRIMARY KEY btree (id)
# -----------------------------------------------------------------------------------------
