class Log < Sequel::Model
end

# Table: logs
# -----------------------------------------------------------------------------------------
# Columns:
#  id          | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  type        | character varying(255)      | NOT NULL
#  finished_at | timestamp without time zone |
#  created_at  | timestamp without time zone | NOT NULL
# Indexes:
#  logs_pkey | PRIMARY KEY btree (id)
# -----------------------------------------------------------------------------------------
