class Stock < Sequel::Model
  many_to_one :exchange
  one_to_many :institution_histories
  one_to_many :insider_histories

  def display_name
    self[:name].split('/')[1]
  end
end

# Table: stocks
# --------------------------------------------------------------------------------------
# Columns:
#  id                      | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name                    | text    | NOT NULL
#  exchange_id             | integer |
#  percent_of_institutions | numeric |
#  ipo_price               | text    |
#  ipo_amount              | numeric |
#  ipo_placement           | text    |
#  ipo_date                | date    |
#  ipo_average_price       | numeric |
#  ipo_placement_number    | numeric |
#  next_earnings_date      | date    |
# Indexes:
#  stocks_pkey     | PRIMARY KEY btree (id)
#  stocks_name_key | UNIQUE btree (name)
# Foreign key constraints:
#  stocks_exchange_id_fkey | (exchange_id) REFERENCES exchanges(id)
# Referenced By:
#  insider_histories     | insiders_stock_id_fkey     | (stock_id) REFERENCES stocks(id)
#  institution_histories | institutions_stock_id_fkey | (stock_id) REFERENCES stocks(id)
# --------------------------------------------------------------------------------------
