class Stock < Sequel::Model
  many_to_one :exchange
  one_to_many :institutions
  one_to_many :insider_histories

  def display_name
    self[:name].split('/')[1]
  end
end

# Table: stocks
# ------------------------------------------------------------------------------------------------
# Columns:
#  id                      | bigint                 | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name                    | character varying(255) | NOT NULL
#  exchange_id             | bigint                 |
#  percent_of_institutions | numeric                |
#  ipo_price               | character varying(255) |
#  ipo_amount              | numeric                |
#  ipo_placement           | character varying(255) |
#  ipo_date                | date                   |
#  ipo_average_price       | numeric                |
#  ipo_placement_number    | numeric                |
#  next_earnings_date      | date                   |
# Indexes:
#  stocks_pkey               | PRIMARY KEY btree (id)
#  sqlite_autoindex_stocks_1 | UNIQUE btree (name)
# Foreign key constraints:
#  stocks_exchange_id_fkey | (exchange_id) REFERENCES exchanges(id)
# Referenced By:
#  insider_histories | insiders_stock_id_fkey     | (stock_id) REFERENCES stocks(id)
#  institutions      | institutions_stock_id_fkey | (stock_id) REFERENCES stocks(id)
# ------------------------------------------------------------------------------------------------
